# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043d\u0442', 'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043d\u0442\u044b'},
        ),
    ]
