# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '\u041f\u0440\u043e\u0435\u043a\u0442', 'verbose_name_plural': '\u041f\u0440\u043e\u0435\u043a\u0442\u044b/\u041e\u0431\u044a\u0435\u043a\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': '\u041e\u043a\u0440\u0443\u0433', 'verbose_name_plural': '\u041e\u043a\u0440\u0443\u0433\u0430 (\u0434\u043b\u044f \u0438\u043d\u0442\u0435\u0440\u0430\u043d\u0442\u0438\u0432\u043d\u043e\u0439 \u043a\u0430\u0440\u0442\u044b)'},
        ),
    ]
