# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:45
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170619_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='svgpath',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
