# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170623_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='svgpath',
            field=models.TextField(),
        ),
    ]
