# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170623_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='html_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
