# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsMessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmessage',
            options={'verbose_name': '\u0417\u0430\u043f\u0438\u0441\u044c', 'verbose_name_plural': '\u0417\u0430\u043f\u0438\u0441\u0438'},
        ),
    ]
