# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 19:12
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsMessage', '0008_newsmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmessage',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
