# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsMessage', '0009_auto_20170614_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmessage',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
