# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_auto_20170614_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='group',
            new_name='GroupServices',
        ),
    ]
