# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_groupservices_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupservices',
            options={'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430 \u0443\u0441\u043b\u0443\u0433', 'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b \u0443\u0441\u043b\u0443\u0433'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '\u0423\u0441\u043b\u0443\u0433\u0430', 'verbose_name_plural': '\u0423\u0441\u043b\u0443\u0433\u0438'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='max_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='service',
            name='min_text',
        ),
    ]
