# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': '\u041e \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438', 'verbose_name_plural': '\u041e \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'},
        ),
    ]
