# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_auto_20170616_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='licenseImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='license',
            name='img',
        ),
        migrations.AddField(
            model_name='licenseimg',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.license'),
        ),
    ]
