# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_auto_20170616_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseimg',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
