# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_licenseimg_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': '\u041b\u0438\u0446\u0435\u043d\u0437\u0438\u044f', 'verbose_name_plural': '\u041b\u0438\u0446\u0435\u043d\u0437\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='licenseimg',
            options={'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u043b\u0438\u0446\u0435\u043d\u0437\u0438\u0439', 'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u043b\u0438\u0446\u0435\u043d\u0437\u0438\u0439'},
        ),
    ]
