# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_auto_20170619_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupLicenseImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.license')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430 \u043a\u0430\u0440\u0442\u0438\u043d\u043e\u043a \u043b\u0438\u0446\u0435\u043d\u0437\u0438\u0438',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b \u043a\u0430\u0440\u0442\u0438\u043d\u043e\u043a \u043b\u0438\u0446\u0435\u043d\u0437\u0438\u0439',
            },
        ),
        migrations.AlterModelOptions(
            name='licenseimg',
            options={'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u043b\u0438\u0446\u0435\u043d\u0437\u0438\u0438', 'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u043b\u0438\u0446\u0435\u043d\u0437\u0438\u0439'},
        ),
        migrations.RemoveField(
            model_name='licenseimg',
            name='license',
        ),
        migrations.AddField(
            model_name='licenseimg',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='license.groupLicenseImg'),
            preserve_default=False,
        ),
    ]
