# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_auto_20170620_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplicenseimg',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='license',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='licenseimg',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
